mindmap
  root((Knowledge Sources))
    Documents
      PDF
      Word
      Excel
    Systems
      CRM
      ERP
      POS
    Databases
    APIs
    Notion
    SharePoint
    Google Drive
    Websites
