flowchart TB
CASE[Caso de Negocio]
GOAL[Objetivo]
STATUS[Estado]
OUTCOME[Resultado]
CTX[Contexto]
PRI[Prioridad]
FOLLOW[Seguimiento]
ACT[Acción]
ARES[Resultado Acción]
CASE-->GOAL
CASE-->STATUS
CASE-->OUTCOME
CASE-->CTX
CASE-->PRI
CASE-->FOLLOW
ACT-->ARES
