mindmap
 root((BotWA Starter))
  Gestión Conversacional
  Gestión de Decisiones
  Gestión del Conocimiento
  Gestión Comercial
  Gestión de Automatizaciones
  Gestión Analítica
  Administración de la Plataforma
